// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location       string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartTime      int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalSeats     int32                  `protobuf:"varint,7,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,8,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	Price          int64                  `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	MinPrice       int64                  `protobuf:"varint,10,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice       int64                  `protobuf:"varint,11,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Event) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Event) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *Event) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *Event) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Event) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *Event) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type SeatCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatCategory) Reset() {
	*x = SeatCategory{}
	mi := &file_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatCategory) ProtoMessage() {}

func (x *SeatCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatCategory.ProtoReflect.Descriptor instead.
func (*SeatCategory) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *SeatCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeatCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeatCategory) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeatCategory) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                              // "A1"
	RowLabel      string                 `protobuf:"bytes,3,opt,name=row_label,json=rowLabel,proto3" json:"row_label,omitempty"`        // "A"
	SeatNumber    int32                  `protobuf:"varint,4,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` // 1
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *Seat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seat) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Seat) GetRowLabel() string {
	if x != nil {
		return x.RowLabel
	}
	return ""
}

func (x *Seat) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

func (x *Seat) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Seat) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Seat) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetSeatMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatMapRequest) Reset() {
	*x = GetSeatMapRequest{}
	mi := &file_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatMapRequest) ProtoMessage() {}

func (x *GetSeatMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatMapRequest.ProtoReflect.Descriptor instead.
func (*GetSeatMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeatMapRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetSeatMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*SeatCategory        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatMapResponse) Reset() {
	*x = GetSeatMapResponse{}
	mi := &file_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatMapResponse) ProtoMessage() {}

func (x *GetSeatMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatMapResponse.ProtoReflect.Descriptor instead.
func (*GetSeatMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeatMapResponse) GetCategories() []*SeatCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetSeatMapResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type ReserveSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []int64                `protobuf:"varint,2,rep,packed,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatsRequest) Reset() {
	*x = ReserveSeatsRequest{}
	mi := &file_proto_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatsRequest) ProtoMessage() {}

func (x *ReserveSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatsRequest.ProtoReflect.Descriptor instead.
func (*ReserveSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveSeatsRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ReserveSeatsRequest) GetSeatIds() []int64 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *ReserveSeatsRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReserveSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserved      bool                   `protobuf:"varint,1,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ReservedSeats []*Seat                `protobuf:"bytes,4,rep,name=reserved_seats,json=reservedSeats,proto3" json:"reserved_seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatsResponse) Reset() {
	*x = ReserveSeatsResponse{}
	mi := &file_proto_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatsResponse) ProtoMessage() {}

func (x *ReserveSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatsResponse.ProtoReflect.Descriptor instead.
func (*ReserveSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveSeatsResponse) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ReserveSeatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveSeatsResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ReserveSeatsResponse) GetReservedSeats() []*Seat {
	if x != nil {
		return x.ReservedSeats
	}
	return nil
}

type ReleaseSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatsRequest) Reset() {
	*x = ReleaseSeatsRequest{}
	mi := &file_proto_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatsRequest) ProtoMessage() {}

func (x *ReleaseSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseSeatsRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReleaseSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatsResponse) Reset() {
	*x = ReleaseSeatsResponse{}
	mi := &file_proto_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatsResponse) ProtoMessage() {}

func (x *ReleaseSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseSeatsResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ReleaseSeatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSeatsRequest) Reset() {
	*x = ConfirmSeatsRequest{}
	mi := &file_proto_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSeatsRequest) ProtoMessage() {}

func (x *ConfirmSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSeatsRequest.ProtoReflect.Descriptor instead.
func (*ConfirmSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmSeatsRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSeatsResponse) Reset() {
	*x = ConfirmSeatsResponse{}
	mi := &file_proto_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSeatsResponse) ProtoMessage() {}

func (x *ConfirmSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSeatsResponse.ProtoReflect.Descriptor instead.
func (*ConfirmSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmSeatsResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *ConfirmSeatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_proto_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{11}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaginationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	PageLimit     int32                  `protobuf:"varint,4,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMetadata) Reset() {
	*x = PaginationMetadata{}
	mi := &file_proto_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMetadata) ProtoMessage() {}

func (x *PaginationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMetadata.ProtoReflect.Descriptor instead.
func (*PaginationMetadata) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{12}
}

func (x *PaginationMetadata) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginationMetadata) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationMetadata) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationMetadata) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_proto_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Meta          *PaginationMetadata    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_proto_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsResponse) GetMeta() *PaginationMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetEventDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDetailRequest) Reset() {
	*x = GetEventDetailRequest{}
	mi := &file_proto_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDetailRequest) ProtoMessage() {}

func (x *GetEventDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDetailRequest.ProtoReflect.Descriptor instead.
func (*GetEventDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{15}
}

func (x *GetEventDetailRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetEventDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDetailResponse) Reset() {
	*x = GetEventDetailResponse{}
	mi := &file_proto_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDetailResponse) ProtoMessage() {}

func (x *GetEventDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDetailResponse.ProtoReflect.Descriptor instead.
func (*GetEventDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{16}
}

func (x *GetEventDetailResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_proto_event_proto protoreflect.FileDescriptor

const file_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x11proto/event.proto\x12\x05event\"\xbd\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vtotal_seats\x18\a \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\b \x01(\x05R\x0eavailableSeats\x12\x14\n" +
	"\x05price\x18\t \x01(\x03R\x05price\x12\x1b\n" +
	"\tmin_price\x18\n" +
	" \x01(\x03R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\v \x01(\x03R\bmaxPrice\"^\n" +
	"\fSeatCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"\xd5\x01\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1b\n" +
	"\trow_label\x18\x03 \x01(\tR\browLabel\x12\x1f\n" +
	"\vseat_number\x18\x04 \x01(\x05R\n" +
	"seatNumber\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\".\n" +
	"\x11GetSeatMapRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"l\n" +
	"\x12GetSeatMapResponse\x123\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x13.event.SeatCategoryR\n" +
	"categories\x12!\n" +
	"\x05seats\x18\x02 \x03(\v2\v.event.SeatR\x05seats\"j\n" +
	"\x13ReserveSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\x03R\aseatIds\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\"\xa3\x01\n" +
	"\x14ReserveSeatsResponse\x12\x1a\n" +
	"\breserved\x18\x01 \x01(\bR\breserved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x122\n" +
	"\x0ereserved_seats\x18\x04 \x03(\v2\v.event.SeatR\rreservedSeats\"4\n" +
	"\x13ReleaseSeatsRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"L\n" +
	"\x14ReleaseSeatsResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x13ConfirmSeatsRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"N\n" +
	"\x14ConfirmSeatsResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x98\x01\n" +
	"\x12PaginationMetadata\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x04 \x01(\x05R\tpageLimit\"L\n" +
	"\x10GetEventsRequest\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.event.PaginationRequestR\n" +
	"pagination\"h\n" +
	"\x11GetEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.event.PaginationMetadataR\x04meta\"2\n" +
	"\x15GetEventDetailRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"<\n" +
	"\x16GetEventDetailResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event2\xb9\x03\n" +
	"\fEventService\x12>\n" +
	"\tGetEvents\x12\x17.event.GetEventsRequest\x1a\x18.event.GetEventsResponse\x12M\n" +
	"\x0eGetEventDetail\x12\x1c.event.GetEventDetailRequest\x1a\x1d.event.GetEventDetailResponse\x12A\n" +
	"\n" +
	"GetSeatMap\x12\x18.event.GetSeatMapRequest\x1a\x19.event.GetSeatMapResponse\x12F\n" +
	"\vReserveSeat\x12\x1a.event.ReserveSeatsRequest\x1a\x1b.event.ReserveSeatsResponse\x12F\n" +
	"\vReleaseSeat\x12\x1a.event.ReleaseSeatsRequest\x1a\x1b.event.ReleaseSeatsResponse\x12G\n" +
	"\fConfirmSeats\x12\x1a.event.ConfirmSeatsRequest\x1a\x1b.event.ConfirmSeatsResponseB\x14Z\x12shared/proto/eventb\x06proto3"

var (
	file_proto_event_proto_rawDescOnce sync.Once
	file_proto_event_proto_rawDescData []byte
)

func file_proto_event_proto_rawDescGZIP() []byte {
	file_proto_event_proto_rawDescOnce.Do(func() {
		file_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)))
	})
	return file_proto_event_proto_rawDescData
}

var file_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_event_proto_goTypes = []any{
	(*Event)(nil),                  // 0: event.Event
	(*SeatCategory)(nil),           // 1: event.SeatCategory
	(*Seat)(nil),                   // 2: event.Seat
	(*GetSeatMapRequest)(nil),      // 3: event.GetSeatMapRequest
	(*GetSeatMapResponse)(nil),     // 4: event.GetSeatMapResponse
	(*ReserveSeatsRequest)(nil),    // 5: event.ReserveSeatsRequest
	(*ReserveSeatsResponse)(nil),   // 6: event.ReserveSeatsResponse
	(*ReleaseSeatsRequest)(nil),    // 7: event.ReleaseSeatsRequest
	(*ReleaseSeatsResponse)(nil),   // 8: event.ReleaseSeatsResponse
	(*ConfirmSeatsRequest)(nil),    // 9: event.ConfirmSeatsRequest
	(*ConfirmSeatsResponse)(nil),   // 10: event.ConfirmSeatsResponse
	(*PaginationRequest)(nil),      // 11: event.PaginationRequest
	(*PaginationMetadata)(nil),     // 12: event.PaginationMetadata
	(*GetEventsRequest)(nil),       // 13: event.GetEventsRequest
	(*GetEventsResponse)(nil),      // 14: event.GetEventsResponse
	(*GetEventDetailRequest)(nil),  // 15: event.GetEventDetailRequest
	(*GetEventDetailResponse)(nil), // 16: event.GetEventDetailResponse
}
var file_proto_event_proto_depIdxs = []int32{
	1,  // 0: event.GetSeatMapResponse.categories:type_name -> event.SeatCategory
	2,  // 1: event.GetSeatMapResponse.seats:type_name -> event.Seat
	2,  // 2: event.ReserveSeatsResponse.reserved_seats:type_name -> event.Seat
	11, // 3: event.GetEventsRequest.pagination:type_name -> event.PaginationRequest
	0,  // 4: event.GetEventsResponse.events:type_name -> event.Event
	12, // 5: event.GetEventsResponse.meta:type_name -> event.PaginationMetadata
	0,  // 6: event.GetEventDetailResponse.event:type_name -> event.Event
	13, // 7: event.EventService.GetEvents:input_type -> event.GetEventsRequest
	15, // 8: event.EventService.GetEventDetail:input_type -> event.GetEventDetailRequest
	3,  // 9: event.EventService.GetSeatMap:input_type -> event.GetSeatMapRequest
	5,  // 10: event.EventService.ReserveSeat:input_type -> event.ReserveSeatsRequest
	7,  // 11: event.EventService.ReleaseSeat:input_type -> event.ReleaseSeatsRequest
	9,  // 12: event.EventService.ConfirmSeats:input_type -> event.ConfirmSeatsRequest
	14, // 13: event.EventService.GetEvents:output_type -> event.GetEventsResponse
	16, // 14: event.EventService.GetEventDetail:output_type -> event.GetEventDetailResponse
	4,  // 15: event.EventService.GetSeatMap:output_type -> event.GetSeatMapResponse
	6,  // 16: event.EventService.ReserveSeat:output_type -> event.ReserveSeatsResponse
	8,  // 17: event.EventService.ReleaseSeat:output_type -> event.ReleaseSeatsResponse
	10, // 18: event.EventService.ConfirmSeats:output_type -> event.ConfirmSeatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_event_proto_init() }
func file_proto_event_proto_init() {
	if File_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_proto_goTypes,
		DependencyIndexes: file_proto_event_proto_depIdxs,
		MessageInfos:      file_proto_event_proto_msgTypes,
	}.Build()
	File_proto_event_proto = out.File
	file_proto_event_proto_goTypes = nil
	file_proto_event_proto_depIdxs = nil
}
